blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import post_list, post_detail, post_create, post_update, post_delete

urlpatterns = [
    url(r'^$',post_list,name='post-list'),
    url(r'^blog/(?P<id>\d+)/$', post_detail, name='post-detail'),
    url(r'^blog/create/$', post_create, name='post-create'),
    url(r'^blog/(?P<id>\d+)/edit/$', post_update, name='post-update'),
    url(r'^blog/(?P<id>\d+)/delete/$', post_delete, name='post-delete'),
]

verma/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from blog.views import user_login, user_logout, user_register, user_profile, like_post, about
from django.contrib.auth.views import(
	password_reset,
	password_reset_done,
	password_reset_confirm,
	password_reset_complete,
	)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^' ,include('blog.urls', namespace='blog')),
    url(r'^login/$', user_login, name='user-login'),
    url(r'^logout/$', user_logout, name='user-logout'),
    url(r'^register/$', user_register, name='user-register'),
    url(r'^profile/$', user_profile, name='user-profile'),
    url(r'^' ,include('django.contrib.auth.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^like/$', like_post, name='like-post'),
    url(r'^about/$', about, name='about'),
    # url(r'^password-reset/$', password_reset,name='password_reset'),
    # url(r'^password-reset-done/$', password_reset_done,name='password_reset_done'),
    # url(r'^password-reset-confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$', password_reset_confirm, name='password_reset_confirm'),
    # url(r'^password-reset-complete/$', password_reset_complete, name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.utils.text import slugify

# Create your models here.
class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
	STATUS_CHOICES=(
		('draft','Draft'),
		('published','Published')
	)

	title=models.CharField(max_length=120)
	slug=models.SlugField(max_length=120)
	author=models.ForeignKey(User, related_name='blog_posts',on_delete=models.CASCADE)
	likes=models.ManyToManyField(User, related_name='likes', blank=True)
	body=models.TextField()
	image=models.ImageField(upload_to='images/', blank=True, null=True)
	created=models.DateTimeField(auto_now_add=True)
	updated=models.DateTimeField(auto_now=True)
	status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

	objects = models.Manager() #default manager
	published = PublishedManager() #custom model manager
	
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post-detail', kwargs={'id':self.id})

@receiver(pre_save, sender=Post)
def pre_save_slug(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug=slugify(instance.title)

class Profile(models.Model):
	user=models.OneToOneField(User, on_delete=models.CASCADE)
	dob=models.DateField(null=True, blank=True)
	photo=models.ImageField()

	def __str__(self):
		return self.user.username + 'profile'


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)



class Comment(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	post=models.ForeignKey(Post)
	reply=models.ForeignKey('self', null=True, related_name='replies')
	content=models.TextField()
	timestamp=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '{}-{}'.format(self.post.title, self.user.username)

blog/forms.py
from django import forms
from .models import Post,Profile,Comment
from django.contrib.auth.models import User

class PostCreateForm(forms.ModelForm):
	class Meta:
		model=Post
		fields=['title','body','image','status']

class PostEditForm(forms.ModelForm):
	class Meta:
		model=Post
		fields=['title','body','image','status']

class UserLoginForm(forms.Form):
	username=forms.CharField()
	password=forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter your password ...'}))
    confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'confirm password ...'}))
    class Meta:
        model = User
        fields = ( 'username', 'first_name', 'last_name','email', 'password' )

    def clean_confirm_password(self):
    	password=self.cleaned_data.get('password')
    	confirm_password=self.cleaned_data.get('confirm_password')
    	if password != confirm_password:
    		raise forms.ValidationError('Password mismatch')
    	return confirm_password

class UserUpdateForm(forms.ModelForm):
	username=forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
	email=forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
	class Meta:
		model=User
		fields=['username','first_name','last_name', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model=Profile
		fields=['dob', 'photo']

class CommentForm(forms.ModelForm):
	content=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Your text goes here...', 'rows':4, 'cols':30 }))
	class Meta:
		model=Comment
		fields=['content']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, Http404
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post,Profile,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth import authenticate, login, logout
# from django.template.loader import render_to_string
# from django.forms import modelformset_factory
# Create your views here.
def post_list(request):
	post_list=Post.published.all().order_by('-id')
	query=request.GET.get('q')
	print(query)
	if query:
		post_list=Post.published.filter(
			Q(title__icontains=query)|
			Q(body__icontains=query)|
			Q(author__username=query)
			).distinct()
	paginator = Paginator(post_list, 4)
	page=request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	context={
		'posts':posts,
	}
	return render(request,'blog/post_list.html',context)


def post_detail(request, id=None):
	post=get_object_or_404(Post, id=id)
	comments=Comment.objects.filter(post=post, reply=None).order_by('-id')
	is_liked=False
	# print(post.likes)
	# if post.likes.filter(id=request.user.id).exists():
	if request.user in post.likes.all():	
		is_liked=True

	form=CommentForm(request.POST or None)

	if form.is_valid():
		reply_id=request.POST.get('comment_id')
		comment_qs=None
		if reply_id:
			comment_qs=Comment.objects.get(id=reply_id)
		comment=form.save(commit=False)
		comment.post=post
		comment.reply=comment_qs
		comment.user=request.user
		comment.save()
		return redirect(post.get_absolute_url())
	context={
		'post':post,
		'is_liked':is_liked,
		'comments':comments,
		'form':form,
	}
	return render(request,'blog/post_detail.html',context)

def like_post(request):
	post=get_object_or_404(Post, id=request.POST.get('post_id'))
	if post.likes.filter(id=request.user.id).exists():
		post.likes.remove(request.user)
		is_liked=False
	else:
		post.likes.add(request.user)
		is_liked=True
	return redirect(post.get_absolute_url())


@login_required
def post_create(request):
	# ImageFormset=modelformset_factory(Images, fields=('image',), extra=4)
	form=PostCreateForm(request.POST or None, request.FILES or None)
	# formset=ImageFormset(request.POST or None, request.FILES or None)
	if form.is_valid():
		post=form.save(commit=False)
		post.author=request.user
		post.save()
		messages.success(request, 'Post has been successfully created.')
		
		# for f in formset:
		# 	try:
		# 		photo=Images(post=post,image=f.cleaned_data['image'])
		# 		photo.save()
				
		# 	except Exception as e:
		# 		break
		return redirect('blog:post-list')
	context={
		'form':form,
		# 'formset':formset,
	}
	return render(request, 'blog/post_create.html',context)


@login_required
def post_update(request, id):
	post=get_object_or_404(Post, id=id)
	# ImageFormset=modelformset_factory(Images, fields=('image',), extra=4)
	if post.author != request.user:
		raise Http404()
	form=PostEditForm(request.POST or None, request.FILES or None, instance=post)
	# formset=ImageFormset(request.POST or None, request.FILES or None)
	if form.is_valid():
		form.save()
		messages.info(request, 'Post has been Updated successfully.')
		return redirect(post.get_absolute_url())
	context={
		'form':form,
		'post':post,
		# 'formset':formset,
	}
	return render(request, 'blog/post_edit.html', context)

@login_required
def post_delete(request, id):
	post=get_object_or_404(Post, id=id )
	if post.author != request.user:
		raise Http404()
	if request.method=='POST':
		post.delete()
		messages.warning(request, 'Post has been deleted.')
		return redirect('blog:post-list')

	context={
		'object':post,
	}
	return render(request, 'blog/post_delete.html', context)

def user_login(request):
	form=UserLoginForm(request.POST or None)
	if form.is_valid():
		username=form.cleaned_data.get('username')
		password=form.cleaned_data.get('password')
		user=authenticate(username=username, password=password)
		if user:
			if user.is_active:
				login(request, user)
				return redirect('blog:post-list')
			else:
				return HttpResponse('user is not active')
		else:
			return HttpResponse('User is None')

	context={
		'form':form,
	}
	return render(request,'registration/login.html', context)

def user_logout(request):
	logout(request)
	return redirect('user-login')

def user_register(request):
	form=UserRegistrationForm(request.POST or None)
	if form.is_valid():
		user=form.save(commit=False)
		user.set_password(form.cleaned_data['password'])
		user.save()
		return redirect('blog:post-list')
	context={
		'form':form,
	}
	return render(request, 'registration/register.html',context)

@login_required
def user_profile(request):
	user=request.user
	u_form=UserUpdateForm(request.POST or None, instance=user)
	p_form=ProfileUpdateForm(request.POST or None, request.FILES or None, instance=user.profile)
	if u_form.is_valid() and p_form.is_valid():
		u_form.save()
		p_form.save()
		messages.success(request, 'your account has been Updated now.')
		return redirect('blog:post-list')
	context={
		'user':user,
		'u_form':u_form,
		'p_form':p_form,
	}
	return render(request, 'blog/profile.html', context)


def about(request):
	return render(request,'blog/about.html')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
<h2>About Us</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  {% if title %}
  <title>Django {{ title }}</title>
  {% else %}
  <title>Django</title>
  {% endif %}
</head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/main.css' %}">
<body>

<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="{% url 'blog:post-list' %}">Django Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{% url 'blog:post-list' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
            <form class="form-inline" method="" action="{% url 'blog:post-list' %}">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="">New Post</a>
          <a class="nav-item nav-link" href="{% url 'user-profile' %}">Profile</a>
          <div class="dropdown ">
          <a class="nav-link dropdown-toggle"  role="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {% if request.user.profile.photo %}
            <img class="rounded-circle article-img" src="{{ request.user.profile.photo.url }}">
          {% endif %}
          <span>Hi {{request.user|capfirst}}</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'blog:post-create' %}">Create Post</a>
            <a class="dropdown-item" href="{% url 'user-logout' %}">Logout</a>

          </div>
          </div>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'user-login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'user-register' %}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>



<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}{% endblock %}

    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>
<footer class="last container-fluid mt-5">
  <div class="container">
    <div class="row">
      <div class="col-4">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</div>
      <div class="col-4">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</div>
      <div class="col-4">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</div>
    </div> 
  </div>
</footer>
 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script type="text/javascript">
  $(document).ready(function(event){

    $('.reply-btn').click(function(){
      $(this).parent().parent().next('.reply-comment').fadeToggle()
    })

    $(function(){
      setTimeout(function(){
        $('.alert').slideUp(3000);
      },5000);
    });
    $(function(){
      setTimeout(function(){
        $('.first').slideUp(3000);
      },3000);
    });
  })
</script>
</body>
</html>

blog/templates/blog/likes.html
<p>{{post.likes.count}} Like{{post.likes.count|pluralize}}</p>
{% if request.user.is_authenticated %}
<form method="POST" action="{% url 'like-post' %}">
	{% csrf_token %}
	{% if is_liked %}
	<button type="submit" id='like' name="post_id" value="{{post.id}}" class="btn btn-danger">DisLike</button>
	{% else %}
	<button type="submit" id='like' name="post_id" value="{{post.id}}" class="btn btn-success">Like</button>
	{% endif %}

</form>
{% endif %}

blog/templates/blog/post_create.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	<fieldset class="form-group">
		<legend class="border-bottom mb-4">
			Create Blog Post
		</legend>
		{{form|crispy}}
		
	</fieldset>
	<button type="submit" class="btn btn-outline-info">Post</button>
</form>
<div class="border-top mt-3">
	<small>Don't want to create? <a href="#">Cancel</a></small>
</div>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" action="">
	{% csrf_token %}
	<fieldset class="form-group">
		<legend class="border-bottom mb-4">
			Delete Post
		</legend>
		<h2>Are you sure you want to delete "{{object.title}}"</h2>
	</fieldset>
	<button type="submit" class="btn btn-outline-danger">Yes Delete</button>
	<a href="{% url 'blog:post-detail' object.id %}" class="btn btn-outline-secondary">Cancel</a>
</form>


{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<article class="media content-section">
  <!-- <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}"> -->
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="">Author: {{ post.author }}</a>
      <small class="text-muted">{{ post.created|date:'F d, Y' }}</small>
      {% if post.author.profile.photo %}
      <img class="rounded-circle author-img" src="{{ post.author.profile.photo.url }}">
      {% endif %}  
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    {% if post.image  %}
    <img class="img-thumbnail" src="{{ post.image.url }}">
    {% endif %}
    <p class="article-content">{{ post.body }}</p> 
APP ID: 355986108392774
  </div>
</article>

<!-- <div class="row gallery">
  {% for p in post.images_set.all %}
    <div class="col-md-3">
      <img src="{{p.image.url}}" alt="img not found" class="img-thumbnail">
    </div>
  {% endfor %} 
</div> -->

{% include 'blog/likes.html' %}<br>

{% if post.author == request.user %}
<a href="{% url 'blog:post-update' post.id %}" class="btn btn-outline-success btn-md mb-1">Update</a>
<a href="{% url 'blog:post-delete' post.id %}" class="btn btn-outline-danger btn-md mb-1">Delete</a>
{% endif %}
<hr>

<form method="POST" action="">
  {% csrf_token %}
  {{form|crispy}}
  {% if request.user.is_authenticated %}
  <input type="submit" value="Submit" class="btn btn-primary">
  {% else %}
  <input type="submit" value="Submit" class="btn btn-outline-primary" disabled>
  {% endif %}
</form>
<hr>
<div class="comment-section">  
  {{comments.count}}: Comment{{comments|pluralize}}
  {% for comment in comments %}
  <blockquote class="blockquote">
    <p class="mb-0"><small>{{comment.content}}</small></p>
    <footer class="blockquote-footer"><small>by: <cite title="Source Title">{{comment.user|capfirst}}</cite></small>
       {% if request.user.is_authenticated %}
      <button type="button" class="reply-btn btn btn-outline-secondary btn-sm ml-3">Reply</button> 
      {% else %}
      <button type="button" class="reply-btn btn btn-outline-secondary btn-sm ml-3" disabled>Reply</button> 
      {% endif %}
    </footer>
    
  </blockquote>

  <div class="reply-comment container ml-4" style="display: none;">
    {% for reply in comment.replies.all %}
    <blockquote class="blockquote">
      <p class="mb-0"><small>{{reply.content}}</small></p>
      <footer class="blockquote-footer"><small>by: <cite title="Source Title">{{reply.user|capfirst}}</cite></small></footer>
     <!--  <a href="#" class="btn btn-outline-secondary">Reply</a> -->
    </blockquote>
    {% endfor %}
    <div class="form-group row">
      <form method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="comment_id" value="{{comment.id}}">
      {{form|crispy}}
      {% if request.user.is_authenticated %}
      <input type="submit" value="Submit" class="btn btn-primary">
      {% else %}
      <input type="submit" value="Submit" class="btn btn-outline-primary" disabled>
      {% endif %}
      </form>
    </div> 
  </div>

  {% endfor %}
</div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	<fieldset class="form-group">
		<legend class="border-bottom mb-4">
			Edit Blog Post
		</legend>
		{{form|crispy}}
		<!-- {{formset.management_form}}
		{% for f in formset %}
		{{f.as_p}}
		{% endfor %} -->
		
	</fieldset>
	<button type="submit" class="btn btn-outline-info">Update</button>
</form>
<div class="border-top mt-3">
	<small>Don't want to Update? <a href="#">Cancel</a></small>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
{% if request.user.is_authenticated %}
<div class="row first">
	<div class="col-sm-12 mb-3">
		<h4 class="text-center">Welcome {{ user.username }}</h4>
	</div>
	<!-- Add from here -->
	{% for ass in backends.associated %}
		{% if ass.provider == 'facebook' %}
		<div class="col-md-6 text-center">
			<img src="{{ass.extra_data.picture.data.url}}" alt="" width="150" height="150" style="border-radius: 50%">
		</div>
		<div class="col-md-6 social-container my-2">                 
			<p> Signed in via:  {{ ass.provider }} </p>
			<p> Name:  {{ ass.extra_data.name }} </p>
			<p> Provider url: <a href="{{ass.extra_data.profile_url}}">link</a></p>
		</div>
		{% endif %}
		<!-- Add from here -->
		{% if ass.provider == 'instagram' %}
		<div class="col-md-6 text-center">      
		    <img src="{{ ass.extra_data.user.profile_picture }}" alt="" width="150" height="150" style="border-radius: 50%">             
		</div>
		<div class="col-md-6 social-container my-2">
			<p>Signed in via: {{ ass.provider }} </p>
			<p> Name:  {{ ass.extra_data.user.full_name }} </p>
			<p>Provider url: <a href="https://instagram.com/{{ ass.username }}">link</a></p>
		</div>
		{% endif %}
	{% endfor %}
</div><br>
{% endif %}

{% for post in posts %}
<article class="media content-section">
{% if post.author.profie.photo %}
<img class="rounded-circle article-img" src="{{post.author.profile.photo.url}}">
{% endif %}
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="">Author: {{ post.author }}</a>
      <small class="text-muted">{{ post.created|date:'F d, Y' }}</small>
    </div>
    <h2><a class="article-title" href="{{post.get_absolute_url}}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.body| truncatewords:30}}</p>
  </div>
</article>
{% empty%}
<h3>Sorry! No post found..</h3>
{% endfor %} 

<ul class="pagination" style="margin-left: 30%" >
	{% if posts.has_previous %}
	<li class="page-item"><a href="?page={{posts.previous_page_number}}" class="page-link">&laquo;</a></li>
	{% endif %}
    {% for post in posts.paginator.page_range %}
    	{% if posts.number == post %}
    	<li class="page-item active"><a href="?page={{post}}" class="page-link">{{post}}</a></li>
    	{% elif post > posts.number|add:'-3' or post < posts.number|add:'3' %}
    	<li class="page-item"><a href="?page={{post}}" class="page-link">{{post}}</a></li>
    	{% endif %}
    {% endfor %}
    {% if posts.has_next %}
	<li class="page-item"><a href="?page={{posts.next_page_number}}" class="page-link">&raquo;</a></li>
	{% endif %}
</ul>

{% endblock %}
  
 

blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

 <div class="content-section">
    <div class="media">
    	{% if user.profile.photo %}
        <img class="rounded-circle account-img" src="{{ user.profile.photo.url }}">
        {% endif %}
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
    </div>
    <div>
      	<form method="POST" action="" enctype="multipart/form-data">
      		{% csrf_token %}
      		<fieldset class="form-group">
      			<legend class="border-bottom mb-4">
      				Update Profile
      			</legend>
      			{{u_form|crispy}}
      			{{p_form|crispy}}
      		</fieldset>
      		<button type="submit" class="btn btn-outline-info">Update</button>
      	</form>
    </div>
</div>
{% endblock %}